export type MobileRouteClassification = 1 | 2 | 3 | 4;

export type MobileRouteResolution = "preserve" | "redesign" | "specialist" | "redirect";

export type MobileRouteAuditEntry = {
  file: string;
  route: string;
  classification: MobileRouteClassification;
  resolution: MobileRouteResolution;
  note: string;
};

/**
 * Complete authenticated and private-share mobile audit inventory.
 *
 * Classification:
 * 1 = genuinely mobile-native; preserve with bounded polish
 * 2 = Apple styled but structurally desktop-derived; refine the composition
 * 3 = poor or overly dense on mobile; purpose-built mobile IA required
 * 4 = specialist visualisation/task canvas; preserve it and redesign its shell
 */
export const mobileRouteAudit = [
  {
    file: "src/app/(app)/companion-runtime/import/csv/page.tsx",
    route: "/companion-runtime/import/csv",
    classification: 1,
    resolution: "preserve",
    note: "Internal authenticated rewrite isolates the full CSV companion workflow from the default import source bundle.",
  },
  {
    file: "src/app/(app)/companion-runtime/import/page.tsx",
    route: "/companion-runtime/import",
    classification: 1,
    resolution: "preserve",
    note: "Internal authenticated rewrite isolates the fast companion CSV source flow from the workbench bundle.",
  },
  {
    file: "src/app/(app)/companion-runtime/import/result/page.tsx",
    route: "/companion-runtime/import/result",
    classification: 1,
    resolution: "preserve",
    note: "Internal authenticated rewrite isolates the immediate mobile verdict and chart review.",
  },
  {
    file: "src/app/(app)/companion-runtime/rapsodo/page.tsx",
    route: "/companion-runtime/rapsodo",
    classification: 1,
    resolution: "preserve",
    note: "Internal authenticated rewrite loads only the recent-session R-Cloud companion client.",
  },
  {
    file: "src/app/(app)/companion/summary/page.tsx",
    route: "/companion/summary",
    classification: 1,
    resolution: "preserve",
    note: "Approved summary routes render read-only current-state rows without loading their workbenches.",
  },
  {
    file: "src/app/(app)/sessions/[sessionId]/page.tsx",
    route: "/sessions/[sessionId]",
    classification: 1,
    resolution: "preserve",
    note: "Compact measured practice review shows verdict, four metrics, dispersion, trajectory and next action.",
  },
  {
    file: "src/app/(app)/companion/handoff/page.tsx",
    route: "/companion/handoff",
    classification: 1,
    resolution: "preserve",
    note: "Desktop-only phone requests receive an early lightweight handoff and companion alternatives.",
  },
  {
    file: "src/app/(app)/play/page.tsx",
    route: "/play",
    classification: 1,
    resolution: "preserve",
    note: "Companion Play hub leads with selected-course readiness, strategy and Course Twin.",
  },
  {
    file: "src/app/(app)/quick-bag/page.tsx",
    route: "/quick-bag",
    classification: 1,
    resolution: "preserve",
    note: "Quick Bag loads only trusted measured yardages for club and target-distance lookup.",
  },
  {
    file: "src/app/(admin)/admin/billing/page.tsx",
    route: "/admin/billing",
    classification: 3,
    resolution: "redesign",
    note: "Subscription, entitlement and limits tables need segmented mobile rows and sheets.",
  },
  {
    file: "src/app/(admin)/admin/challenges/page.tsx",
    route: "/admin/challenges",
    classification: 3,
    resolution: "redesign",
    note: "Open and flagged boards must lead; templates and filters are secondary.",
  },
  {
    file: "src/app/(admin)/admin/moderation/page.tsx",
    route: "/admin/moderation",
    classification: 3,
    resolution: "redesign",
    note: "Safety queues need urgent-first rows and focused resolution sheets.",
  },
  {
    file: "src/app/(admin)/admin/page.tsx",
    route: "/admin",
    classification: 3,
    resolution: "redesign",
    note: "Operational failures and queues must outrank dashboard cards and unsupported health claims.",
  },
  {
    file: "src/app/(admin)/admin/system-checks/page.tsx",
    route: "/admin/system-checks",
    classification: 3,
    resolution: "redesign",
    note: "Failed and unmeasured checks need native rows instead of a wide table.",
  },
  {
    file: "src/app/(admin)/admin/users/page.tsx",
    route: "/admin/users",
    classification: 3,
    resolution: "redesign",
    note: "Search and account rows must precede owner-only grant controls.",
  },
  {
    file: "src/app/(app)/achievements/page.tsx",
    route: "/achievements",
    classification: 2,
    resolution: "redesign",
    note: "Next unlock leads; cabinet, catalogue and history become compact drill-down rows.",
  },
  {
    file: "src/app/(app)/analyse/compare/page.tsx",
    route: "/analyse/compare",
    classification: 4,
    resolution: "redirect",
    note: "Session comparison is desktop-only; companion requests hand off to the dedicated Sessions route.",
  },
  {
    file: "src/app/(app)/analyse/conditions/page.tsx",
    route: "/analyse/conditions",
    classification: 3,
    resolution: "redesign",
    note: "Condition conclusion leads; desktop tables become disclosure metric rows.",
  },
  {
    file: "src/app/(app)/analyse/page.tsx",
    route: "/analyse",
    classification: 4,
    resolution: "redirect",
    note: "Deep analysis is desktop-only; companion requests hand off to the dedicated Sessions route.",
  },
  {
    file: "src/app/(app)/analyse/session-impact/page.tsx",
    route: "/analyse/session-impact",
    classification: 4,
    resolution: "specialist",
    note: "Preserve shot-path comparison; put its verdict and recommendation before controls and map.",
  },
  {
    file: "src/app/(app)/analyse/workspace/page.tsx",
    route: "/analyse/workspace",
    classification: 3,
    resolution: "redesign",
    note: "Use one real segmented workspace instead of rendering all four tools sequentially.",
  },
  {
    file: "src/app/(app)/bag/[clubId]/analytics/page.tsx",
    route: "/bag/[clubId]/analytics",
    classification: 4,
    resolution: "specialist",
    note: "Keep shot cloud and charts; surface recommendation/warning and replace the evidence table on phone.",
  },
  {
    file: "src/app/(app)/bag/[clubId]/page.tsx",
    route: "/bag/[clubId]",
    classification: 4,
    resolution: "specialist",
    note: "Preserve dispersion and trajectory; use one pushed detail hierarchy and one-level evidence sections.",
  },
  {
    file: "src/app/(app)/bag/longest/page.tsx",
    route: "/bag/longest",
    classification: 4,
    resolution: "specialist",
    note: "Preserve the replay simulator and add compact club/evidence rows around it.",
  },
  {
    file: "src/app/(app)/bag/page.tsx",
    route: "/bag",
    classification: 2,
    resolution: "redesign",
    note: "Bag summary and native club list lead; deep fitting and evidence remain secondary.",
  },
  {
    file: "src/app/(app)/billing/page.tsx",
    route: "/billing",
    classification: 3,
    resolution: "redesign",
    note: "Current membership and portal lead; comparison and limits become disclosures/rows.",
  },
  {
    file: "src/app/(app)/challenges/[challengeId]/page.tsx",
    route: "/challenges/[challengeId]",
    classification: 1,
    resolution: "preserve",
    note: "Retain the pushed result/CTA/tabs; add complete mobile standings and invite access.",
  },
  {
    file: "src/app/(app)/challenges/page.tsx",
    route: "/challenges",
    classification: 3,
    resolution: "redesign",
    note: "Filtered active challenge leads once; remaining real rows and history are compact.",
  },
  {
    file: "src/app/(app)/coach/diagnosis/page.tsx",
    route: "/coach/diagnosis",
    classification: 3,
    resolution: "redesign",
    note: "Top club issue and retest lead; diagnosis table becomes native issue rows.",
  },
  {
    file: "src/app/(app)/coach/page.tsx",
    route: "/coach",
    classification: 1,
    resolution: "preserve",
    note: "Existing conclusion/action/evidence mobile composition is strong; keep it concise.",
  },
  {
    file: "src/app/(app)/coach/reports/page.tsx",
    route: "/coach/reports",
    classification: 4,
    resolution: "redirect",
    note: "Selective report creation is desktop-only; companion requests hand off to Coach.",
  },
  {
    file: "src/app/(app)/coach/workspace/page.tsx",
    route: "/coach/workspace",
    classification: 4,
    resolution: "redirect",
    note: "The assigned-player workspace is desktop-only; companion requests hand off to Coach.",
  },
  {
    file: "src/app/(app)/compare/page.tsx",
    route: "/compare",
    classification: 4,
    resolution: "redirect",
    note: "Multi-session comparison is desktop-only; companion requests hand off to Sessions.",
  },
  {
    file: "src/app/(app)/course-records/[recordId]/page.tsx",
    route: "/course-records/[recordId]",
    classification: 1,
    resolution: "preserve",
    note: "Keep answer-first status, submit sheet and leaderboard; align breakpoint and touch targets.",
  },
  {
    file: "src/app/(app)/course-records/page.tsx",
    route: "/course-records",
    classification: 2,
    resolution: "redesign",
    note: "Featured target and own status lead; honours boards become the primary list.",
  },
  {
    file: "src/app/(app)/course-twins/page.tsx",
    route: "/course-twins",
    classification: 2,
    resolution: "redesign",
    note: "Use a concise playable-course catalogue and disclose mapping/terrain limitations.",
  },
  {
    file: "src/app/(app)/courses/[courseId]/holes/page.tsx",
    route: "/courses/[courseId]/holes",
    classification: 4,
    resolution: "specialist",
    note: "Keep one map-first selected-hole editor; remove duplicated mobile and batch forms.",
  },
  {
    file: "src/app/(app)/courses/[courseId]/records/[recordId]/page.tsx",
    route: "/courses/[courseId]/records/[recordId]",
    classification: 1,
    resolution: "redirect",
    note: "Canonical record detail alias; inherit the native destination.",
  },
  {
    file: "src/app/(app)/courses/[courseId]/records/page.tsx",
    route: "/courses/[courseId]/records",
    classification: 1,
    resolution: "preserve",
    note: "Keep compact course board/status and submit sheet; align breakpoint and touch targets.",
  },
  {
    file: "src/app/(app)/courses/[courseId]/shot-pattern/page.tsx",
    route: "/courses/[courseId]/shot-pattern",
    classification: 4,
    resolution: "specialist",
    note: "Preserve full-screen dispersion map and make the control sheet collapsible and safe-area aware.",
  },
  {
    file: "src/app/(app)/courses/[courseId]/tournaments/page.tsx",
    route: "/courses/[courseId]/tournaments",
    classification: 2,
    resolution: "redirect",
    note: "Course-filtered tournament alias must retain a real applied course filter.",
  },
  {
    file: "src/app/(app)/courses/new/page.tsx",
    route: "/courses/new",
    classification: 3,
    resolution: "redesign",
    note: "Choose Google, OSM or Manual once, then render exactly one focused import workflow.",
  },
  {
    file: "src/app/(app)/courses/page.tsx",
    route: "/courses",
    classification: 2,
    resolution: "redesign",
    note: "One featured course plus concise searchable course rows replaces the rich-card wall.",
  },
  {
    file: "src/app/(app)/courses/strategy/page.tsx",
    route: "/courses/strategy",
    classification: 3,
    resolution: "redesign",
    note: "Pre- and post-round modes render distinct tasks; compact hole rows reveal selected detail.",
  },
  {
    file: "src/app/(app)/dashboard/page.tsx",
    route: "/dashboard",
    classification: 4,
    resolution: "redirect",
    note: "The analytical dashboard is desktop-only; companion requests hand off to the dedicated Today route.",
  },
  {
    file: "src/app/(app)/data-chat/page.tsx",
    route: "/data-chat",
    classification: 4,
    resolution: "redirect",
    note: "Long-form Data Chat is desktop-only; companion requests hand off to the dedicated Practice route.",
  },
  {
    file: "src/app/(app)/equipment/experiments/page.tsx",
    route: "/equipment/experiments",
    classification: 3,
    resolution: "redesign",
    note: "Verdict and deltas lead; setup selection and decision recording become focused tasks.",
  },
  {
    file: "src/app/(app)/equipment/page.tsx",
    route: "/equipment",
    classification: 2,
    resolution: "redesign",
    note: "Owned equipment becomes a native list with fit/action visible and deeper history disclosed.",
  },
  {
    file: "src/app/(app)/feed/page.tsx",
    route: "/feed",
    classification: 3,
    resolution: "redesign",
    note: "Real current activity leads; remove fabricated goal/proof and restore honest interactions.",
  },
  {
    file: "src/app/(app)/friends/page.tsx",
    route: "/friends",
    classification: 3,
    resolution: "redesign",
    note: "Friends, Requests and Suggestions segments replace repeated panels and tables.",
  },
  {
    file: "src/app/(app)/goals/page.tsx",
    route: "/goals",
    classification: 2,
    resolution: "redesign",
    note: "Weekly evidence and current goals remain visible; edit/add forms use native disclosure.",
  },
  {
    file: "src/app/(app)/groups/[groupSlug]/page.tsx",
    route: "/groups/[groupSlug]",
    classification: 3,
    resolution: "redesign",
    note: "Feed, standing and current challenge lead; members, rules and management drill down.",
  },
  {
    file: "src/app/(app)/groups/page.tsx",
    route: "/groups",
    classification: 2,
    resolution: "redesign",
    note: "All tabs use their real filtered group rows and a compact membership hierarchy.",
  },
  {
    file: "src/app/(app)/handicap/page.tsx",
    route: "/handicap",
    classification: 2,
    resolution: "redesign",
    note: "One estimate/movement/confidence summary leads; evidence sources and method disclose.",
  },
  {
    file: "src/app/(app)/import/page.tsx",
    route: "/import",
    classification: 2,
    resolution: "redesign",
    note: "One compact title and step indicator precede the active upload/mapping task.",
  },
  {
    file: "src/app/(app)/import/result/page.tsx",
    route: "/import/result",
    classification: 3,
    resolution: "redesign",
    note: "Accepted-shot receipt, warnings and next action lead; trust/audit details disclose.",
  },
  {
    file: "src/app/(app)/leaderboard/page.tsx",
    route: "/leaderboard",
    classification: 3,
    resolution: "redesign",
    note: "Board-specific personal position and full native rows replace desktop rank semantics.",
  },
  {
    file: "src/app/(app)/partners/page.tsx",
    route: "/partners",
    classification: 3,
    resolution: "redesign",
    note: "Admin offers and sponsors use segments, rows and focused creation rather than wide forms/tables.",
  },
  {
    file: "src/app/(app)/play/[courseId]/page.tsx",
    route: "/play/[courseId]",
    classification: 4,
    resolution: "specialist",
    note: "Purpose-built immersive 3D runtime is preserved with safe areas, landscape and reduced motion.",
  },
  {
    file: "src/app/(app)/practice/page.tsx",
    route: "/practice",
    classification: 3,
    resolution: "redesign",
    note: "Active block and primary CTA lead; why, evidence, history and ledger disclose.",
  },
  {
    file: "src/app/(app)/practice/quick-range/page.tsx",
    route: "/practice/quick-range",
    classification: 2,
    resolution: "redesign",
    note: "Preserve focused ready/active/finished flow and move plan/method controls behind task UI.",
  },
  {
    file: "src/app/(app)/profile/[username]/page.tsx",
    route: "/profile/[username]",
    classification: 3,
    resolution: "redesign",
    note: "One pushed identity with Overview, Activity and Bag mobile row views.",
  },
  {
    file: "src/app/(app)/profile/page.tsx",
    route: "/profile",
    classification: 2,
    resolution: "redesign",
    note: "Real identity/season metrics and selected tab lead; sharing/data health become secondary.",
  },
  {
    file: "src/app/(app)/progress/page.tsx",
    route: "/progress",
    classification: 3,
    resolution: "redesign",
    note: "Level, momentum, strength, weakness and next action lead; deep journey evidence discloses.",
  },
  {
    file: "src/app/(app)/providers/page.tsx",
    route: "/providers",
    classification: 3,
    resolution: "redesign",
    note: "Connected source and import action lead; provider/session/job tables become rows.",
  },
  {
    file: "src/app/(app)/rapsodo/page.tsx",
    route: "/rapsodo",
    classification: 2,
    resolution: "redesign",
    note: "Keep one-step import flow; move provider health and filters after the active task.",
  },
  {
    file: "src/app/(app)/rounds/[sessionId]/page.tsx",
    route: "/rounds/[sessionId]",
    classification: 3,
    resolution: "redesign",
    note: "Current result/hole leads; round, performance and corrections use accessible disclosure/sheets.",
  },
  {
    file: "src/app/(app)/rounds/new/page.tsx",
    route: "/rounds/new",
    classification: 1,
    resolution: "preserve",
    note: "Purpose-built four-step scoring flow is retained with keyboard-safe actions and review validation.",
  },
  {
    file: "src/app/(app)/rounds/page.tsx",
    route: "/rounds",
    classification: 3,
    resolution: "redesign",
    note: "Latest result/action and concise round rows replace mobile master-detail duplication.",
  },
  {
    file: "src/app/(app)/sessions/page.tsx",
    route: "/sessions",
    classification: 2,
    resolution: "redesign",
    note: "Segmented filter and native date/type/result rows replace rich repeated cards.",
  },
  {
    file: "src/app/(app)/settings/invitations/[token]/page.tsx",
    route: "/settings/invitations/[token]",
    classification: 1,
    resolution: "preserve",
    note: "Keep the focused role-scoped confirmation with clear account mismatch handling.",
  },
  {
    file: "src/app/(app)/settings/notifications/page.tsx",
    route: "/settings/notifications",
    classification: 2,
    resolution: "redesign",
    note: "Delivery values become grouped picker rows and Boolean settings retain native toggles.",
  },
  {
    file: "src/app/(app)/settings/page.tsx",
    route: "/settings",
    classification: 2,
    resolution: "redesign",
    note: "Account, Preferences and Data grouped hierarchy leads; forms and destructive controls drill down.",
  },
  {
    file: "src/app/(app)/shared/[userId]/page.tsx",
    route: "/shared/[userId]",
    classification: 2,
    resolution: "redesign",
    note: "Read-only identity/result and native session rows replace duplicated metric surfaces.",
  },
  {
    file: "src/app/(app)/shots/page.tsx",
    route: "/shots",
    classification: 3,
    resolution: "redesign",
    note: "Latest filtered shots lead; filters, dispersion map and advanced explorer disclose.",
  },
  {
    file: "src/app/(app)/simulator-lab/page.tsx",
    route: "/simulator-lab",
    classification: 3,
    resolution: "specialist",
    note: "Playing estimate/leak/action lead; retain flight, gapping, what-if and timeline canvases as evidence.",
  },
  {
    file: "src/app/(app)/social-intelligence/page.tsx",
    route: "/social-intelligence",
    classification: 3,
    resolution: "redesign",
    note: "Latest recap conclusion leads; generation and safety reporting become contextual tasks/rows.",
  },
  {
    file: "src/app/(app)/speed/page.tsx",
    route: "/speed",
    classification: 3,
    resolution: "redesign",
    note: "Selected-club speed, trend, target gap and action lead; goals/history/all clubs drill down.",
  },
  {
    file: "src/app/(app)/speed/sessions/[sessionId]/page.tsx",
    route: "/speed/sessions/[sessionId]",
    classification: 3,
    resolution: "redesign",
    note: "Average/best/finish lead; swing log, editing and destructive controls separate.",
  },
  {
    file: "src/app/(app)/stats/training-over-time/page.tsx",
    route: "/stats/training-over-time",
    classification: 3,
    resolution: "redesign",
    note: "Readiness/recovery and next 48 hours lead; charts, quality and history disclose.",
  },
  {
    file: "src/app/(app)/strokes-gained/page.tsx",
    route: "/strokes-gained",
    classification: 3,
    resolution: "redesign",
    note: "Total, main leak, best phase, coverage and drill lead; supporting charts/data disclose.",
  },
  {
    file: "src/app/(app)/today/page.tsx",
    route: "/today",
    classification: 2,
    resolution: "redesign",
    note: "Verdict, next action and recent signal lead; club/evidence/raw-shot depth consolidates.",
  },
  {
    file: "src/app/(app)/tournaments/[tournamentId]/leaderboard/page.tsx",
    route: "/tournaments/[tournamentId]/leaderboard",
    classification: 1,
    resolution: "redirect",
    note: "Alias opens the destination's mobile board tab rather than a desktop anchor.",
  },
  {
    file: "src/app/(app)/tournaments/[tournamentId]/page.tsx",
    route: "/tournaments/[tournamentId]",
    classification: 1,
    resolution: "preserve",
    note: "Keep pushed status/submit/tabs and specialist proof flow; add a complete mobile board.",
  },
  {
    file: "src/app/(app)/tournaments/[tournamentId]/rounds/page.tsx",
    route: "/tournaments/[tournamentId]/rounds",
    classification: 1,
    resolution: "redirect",
    note: "Alias opens the destination's mobile submit tab rather than a desktop anchor.",
  },
  {
    file: "src/app/(app)/tournaments/[tournamentId]/rules/page.tsx",
    route: "/tournaments/[tournamentId]/rules",
    classification: 1,
    resolution: "redirect",
    note: "Alias opens the destination's mobile rules tab rather than a desktop anchor.",
  },
  {
    file: "src/app/(app)/tournaments/[tournamentId]/submit/page.tsx",
    route: "/tournaments/[tournamentId]/submit",
    classification: 1,
    resolution: "redirect",
    note: "Alias opens the destination's mobile submit tab rather than a desktop anchor.",
  },
  {
    file: "src/app/(app)/tournaments/page.tsx",
    route: "/tournaments",
    classification: 3,
    resolution: "redesign",
    note: "Real filtered event/title/entry state leads; requirements and past events disclose.",
  },
  {
    file: "src/app/(app)/welcome/page.tsx",
    route: "/welcome",
    classification: 2,
    resolution: "redesign",
    note: "The first incomplete real-data activation step dominates; completed/upcoming steps disclose.",
  },
  {
    file: "src/app/share/[token]/page.tsx",
    route: "/share/[token]",
    classification: 2,
    resolution: "redesign",
    note: "Private score/result leads; eighteen card-like holes become compact score rows.",
  },
  {
    file: "src/app/share/course-twin/[token]/page.tsx",
    route: "/share/course-twin/[token]",
    classification: 4,
    resolution: "specialist",
    note: "Use the same non-collapsing full-viewport runtime contract as authenticated play.",
  },
  {
    file: "src/app/share/report/[token]/page.tsx",
    route: "/share/report/[token]",
    classification: 3,
    resolution: "redesign",
    note: "Preserve private-report language; add a mobile index, section disclosures and table alternatives.",
  },
] as const satisfies readonly MobileRouteAuditEntry[];
