import type { PlanKey } from "@/lib/billing-plan-catalog";

export const planEntitlements = {
  free: [
    ["max_monthly_imports", { value: 5 }],
    ["max_friend_groups", { value: 1 }],
    ["max_private_challenges", { value: 0 }],
    ["can_use_ai_coach", { value: false }],
    ["ai_monthly_credits", { value: 0 }],
    ["ai_daily_chat_messages", { value: 0 }],
    ["ai_scorecard_extracts_monthly", { value: 0 }],
  ],
  plus: [
    ["max_monthly_imports", { value: 999999, label: "Unlimited" }],
    ["max_friend_groups", { value: 8 }],
    ["max_private_challenges", { value: 999999, label: "Unlimited" }],
    ["private_course_record_boards", { value: true }],
    ["private_friend_tournaments", { value: true }],
    ["advanced_reports", { value: true }],
    ["ai_monthly_credits", { value: 10 }],
    ["ai_daily_chat_messages", { value: 0 }],
    ["ai_scorecard_extracts_monthly", { value: 2 }],
  ],
  pro: [
    ["private_course_record_boards", { value: true }],
    ["private_friend_tournaments", { value: true }],
    ["max_monthly_imports", { value: 999999, label: "Unlimited" }],
    ["max_friend_groups", { value: 12 }],
    ["max_private_challenges", { value: 999999, label: "Unlimited" }],
    ["advanced_reports", { value: true }],
    ["can_use_ai_coach", { value: true }],
    ["friend_comparison_insights", { value: true }],
    ["challenge_analytics", { value: true }],
    ["ai_record_strategy", { value: true }],
    ["advanced_verification_analytics", { value: true }],
    ["device_import_square", { value: true }],
    ["device_import_trackman", { value: true }],
    ["ai_monthly_credits", { value: 100 }],
    ["ai_daily_chat_messages", { value: 30 }],
    ["ai_scorecard_extracts_monthly", { value: 10 }],
  ],
  coach: [
    ["ai_record_strategy", { value: true }],
    ["advanced_verification_analytics", { value: true }],
    ["private_course_record_boards", { value: true }],
    ["private_friend_tournaments", { value: true }],
    ["max_monthly_imports", { value: 999999, label: "Unlimited" }],
    ["max_friend_groups", { value: 999999, label: "Unlimited" }],
    ["max_private_challenges", { value: 999999, label: "Unlimited" }],
    ["advanced_reports", { value: true }],
    ["can_use_ai_coach", { value: true }],
    ["friend_comparison_insights", { value: true }],
    ["challenge_analytics", { value: true }],
    ["device_import_square", { value: true }],
    ["device_import_trackman", { value: true }],
    ["coach_dashboard", { value: true }],
    ["host_major_tournaments", { value: true }],
    ["evidence_review_queue", { value: true }],
    ["ai_monthly_credits", { value: 300 }],
    ["ai_daily_chat_messages", { value: 60 }],
    ["ai_scorecard_extracts_monthly", { value: 25 }],
  ],
  full: [
    ["lifetime_full", { value: true }],
    ["max_monthly_imports", { value: 999999, label: "Unlimited" }],
    ["max_friend_groups", { value: 999999, label: "Unlimited" }],
    ["max_private_challenges", { value: 999999, label: "Unlimited" }],
    ["monthly_course_record_attempts", { value: 999999, label: "Unlimited" }],
    ["private_course_record_boards", { value: true }],
    ["private_friend_tournaments", { value: true }],
    ["host_major_tournaments", { value: true }],
    ["can_use_ai_coach", { value: true }],
    ["advanced_reports", { value: true }],
    ["friend_comparison_insights", { value: true }],
    ["challenge_analytics", { value: true }],
    ["ai_record_strategy", { value: true }],
    ["advanced_verification_analytics", { value: true }],
    ["coach_dashboard", { value: true }],
    ["evidence_review_queue", { value: true }],
    ["max_player_seats", { value: 999999, label: "Unlimited" }],
    ["device_import_square", { value: true }],
    ["device_import_trackman", { value: true }],
    ["admin_operations", { value: true }],
    ["ai_monthly_credits", { value: 1000, label: "Internal safety cap" }],
    ["ai_daily_chat_messages", { value: 100 }],
    ["ai_scorecard_extracts_monthly", { value: 50 }],
  ],
} as const satisfies Record<PlanKey, ReadonlyArray<readonly [string, Record<string, unknown>]>>;

export function planNumberLimit(plan: PlanKey, key: string): number {
  const entry = planEntitlements[plan].find(([candidate]) => candidate === key);
  const value = entry?.[1].value;
  return typeof value === "number" ? value : 0;
}
