const hiddenRoutePrefixes = [
  "/login",
  "/auth",
  "/privacy",
  "/play",
  "/share",
  "/shared",
  "/settings/invitations",
  "/feed",
  "/today",
  "/dashboard",
  "/sessions",
  "/progress",
  "/analyse",
  "/bag",
  "/rounds",
  "/strokes-gained",
  "/shots",
  "/compare",
  "/simulator-lab",
  "/speed",
  "/stats/training-over-time",
  "/equipment",
  "/handicap",
  "/courses",
  "/course-records",
  "/tournaments",
  "/practice",
  "/coach",
  "/data-chat",
  "/achievements",
  "/challenges",
  "/import",
  "/rapsodo",
  "/providers",
  "/billing",
  "/settings",
  "/admin",
  "/partners",
];
export function isHiddenRoute(pathname: string) {
  const normalizedPathname = pathname.replace(/\/+$/, "") || "/";
  return hiddenRoutePrefixes.some(
    (prefix) => normalizedPathname === prefix || normalizedPathname.startsWith(`${prefix}/`),
  );
}
